# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Site
site_name: Joseph's personal site
site_url: https://josephpenaquino.github.io/

# Git
repo_url: https://github.com/JosephPenaQuino/JosephPenaQuino.github.io
repo_name: JosephPenaQuino/JosephPenaQuino.github.io

theme:
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  custom_dir: docs/overrides
  language: en
  features:
    - header.autohide  # Auto-hide the header
    - navigation.tabs  # Enable tabs in the navigation bar
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


nav:
  - Home: index.md
  - Projects: projects.md
  - Blog:
    - blog/index.md


plugins:
  - search
  - blog
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags


# Multiple language support
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Spanish
      link: /es/
      lang: es
